name: Build and deploy PHP app with frontend to Azure Web App - pratikumWeb2

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install frontend dependencies and build
        run: |
          npm install
          npm run build

      - name: Check if composer.json exists
        id: check_files
        uses: andstor/file-existence-action@v1
        with:
          files: 'composer.json'

      - name: Run composer install if composer.json exists
        if: steps.check_files.outputs.files_exists == 'true'
        run: composer install --prefer-dist --no-progress

      - name: Prepare deployment folder
        run: |
          mkdir deploy
          cp -r build/* deploy/         # hasil frontend (ubah ke dist/* jika Vue)
          cp -r public/* deploy/        # file PHP (ubah sesuai struktur Anda)
          cp composer.* deploy/         # opsional, jika dibutuhkan
          echo "Deployment files prepared."

      - name: Zip artifact for deployment
        run: |
          cd deploy
          zip -r ../release.zip .

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: php-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: php-app

      - name: Unzip artifact
        run: unzip release.zip

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_3F93063537FA41AA927F8EB0AC9619BB }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_E0663354913947A3B3A0D1A30F011259 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_C01BCAE6EA0943B48FA1575C018A3410 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'pratikumWeb2'
          slot-name: 'Production'
          package: .
